SELECT * FROM STUDENT;

-- 1
INSERT INTO STUDENT
VALUES ('20262015', '박학생', '기계', 1, 'A', 'F', 165, 52);
COMMIT;
-- 2
SELECT * FROM STUDENT
WHERE STU_WEIGHT IS NOT NULL;

-- 3
SELECT * FROM STUDENT
WHERE STU_HEIGHT BETWEEN 160 AND 175;

-- 4
SELECT * FROM STUDENT
WHERE STU_NAME LIKE '이%';

-- 5
SELECT * FROM STUDENT
WHERE STU_DEPT = '기계' AND STU_WEIGHT >= 60;

-- 6
SELECT * FROM STUDENT
WHERE STU_DEPT IN ('컴퓨터정보', '전기전자');

-- 7
UPDATE STUDENT SET 
    STU_HEIGHT = STU_HEIGHT + 3
WHERE STU_NO = '20262015';
COMMIT;
-- 8
DELETE FROM STUDENT
WHERE STU_NO = '20262015';
COMMIT;