SELECT * FROM EMP;

-- 1
SELECT COUNT(*)
FROM EMP 
WHERE TO_CHAR(HIREDATE, 'YY') = '81';
-- TO_CHAR 말고 SUBSTR도 가능!

-- 2
SELECT COUNT(*)
FROM EMP
WHERE SAL+NVL(COMM,0) >= 2500;

-- 3
SELECT JOB, MAX(SAL)
FROM EMP
GROUP BY JOB;

-- 4
SELECT DEPTNO, AVG(SAL)
FROM EMP
GROUP BY DEPTNO
HAVING AVG(SAL) >= 1800;

-- 5
SELECT TO_CHAR(HIREDATE, 'YY') 입사년도, COUNT(*) 사원수
FROM EMP
GROUP BY TO_CHAR(HIREDATE, 'YY');

-- 6
SELECT SUBSTR(JUMIN,3,2) || '월' 태어난달, COUNT(*)
FROM STU
GROUP BY SUBSTR(JUMIN,3,2)
ORDER BY 태어난달;

-- 7
SELECT COUNT(DECODE(SUBSTR(JUMIN, 7, 1),1,1)) 남학생수, COUNT(DECODE(SUBSTR(JUMIN, 7, 1),2,1)) 여학생수
FROM STU;

SELECT * FROM STU;