-- 조인
-- STUDENT 테이블의 STU_NO는 PK(유니크 + NOT NULL)
SELECT * FROM STUDENT;
-- ENROL 테이블의 STU_NO는 FK(STUDENT 테이블의 STU_NO를 참조하는 참조키)
SELECT * FROM ENROL;

SELECT * FROM SUBJECT;

-- 조인의 종류는 여러 개(INNER, OUTER-LEFT/RIGHT, CROSS 기타 등등)
-- INNER 조인 위주로 시작

-- (학번, 이름, 학과) => STUDENT, (점수) => ENROL
SELECT S.STU_NO, S.STU_NAME, S.STU_DEPT, E.ENR_GRADE
FROM STUDENT S INNER JOIN ENROL E
ON S.STU_NO = E.STU_NO;

-- 시험점수 평균
SELECT S.STU_NO, STU_NAME, STU_DEPT, AVG(ENR_GRADE)
FROM STUDENT S INNER JOIN ENROL E
ON S.STU_NO = E.STU_NO
GROUP BY S.STU_NO, STU_NAME, STU_DEPT;

-- (학번, 이름, 학과) => STUDENT, (점수) => ENROL, (과목명) => SUBJECT
-- 각 과목별 점수
SELECT S.STU_NO, STU_NAME, STU_DEPT, ENR_GRADE, SUB_NAME
FROM STUDENT S 
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN SUBJECT SUB ON SUB.SUB_NO = E.SUB_NO
ORDER BY S.STU_NO;


-- 학과별 시험 평균 점수 출력
SELECT * FROM ENROL;
SELECT * FROM SUBJECT;
SELECT * FROM STUDENT;

SELECT STU_DEPT, AVG(ENR_GRADE)
FROM ENROL E 
INNER JOIN STUDENT S ON E.STU_NO = S.STU_NO
GROUP BY STU_DEPT;


SELECT * FROM SALGRADE; -- 급여 : 직원의 SAL
SELECT * FROM EMP; -- 직원 : DEPTNO
SELECT * FROM DEPT; -- 부서 : DEPTNO

-- 사번, 이름, 부서 번호, 부서이름 출력
SELECT EMPNO, ENAME, E.DEPTNO, DNAME
FROM EMP E 
INNER JOIN DEPT D
ON E.DEPTNO = D.DEPTNO;

-- 조인은 꼭 값이 같은 컬럼끼리 하는 건 아니다.
-- 사원들의 급여 등급 출력(사번, 이름, 급여, 급여등급 출력)
SELECT EMPNO, ENAME, SAL, GRADE
FROM EMP E
INNER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL;

-- 각 부서별 급여 평균 등급 출력
-- (부서번호, 부서이름, 급여 등급 출력)
SELECT D.DEPTNO, D.DNAME, TRUNC(AVG(S.GRADE))
FROM EMP E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
INNER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL
GROUP BY D.DEPTNO, D.DNAME
ORDER BY DEPTNO;


-- 문제
SELECT * FROM STUDENT;
SELECT * FROM ENROL;
SELECT * FROM SUBJECT;
-- 1
SELECT SUB_NAME, AVG(ENR_GRADE)
FROM SUBJECT S
INNER JOIN ENROL E ON S.SUB_NO = E.SUB_NO
GROUP BY SUB_NAME;

-- 2
SELECT S.STU_NO, S.STU_NAME, AVG(ENR_GRADE)
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY S.STU_NO, S.STU_NAME
HAVING AVG(ENR_GRADE) >= 60;

-- 3
SELECT STU_NAME, COUNT(S.STU_NO) 시험개수
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY S.STU_NO, STU_NAME
HAVING COUNT(S.STU_NO) >= 2;

-- 4
SELECT S.STU_NO, STU_NAME,STU_DEPT, ENR_GRADE
FROM STUDENT S 
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN SUBJECT SUB ON SUB.SUB_NO = E.SUB_NO
WHERE SUB_PROF = '강종영';

SELECT * FROM SALGRADE; -- 급여 : 직원의 SAL
SELECT * FROM EMP; -- 직원 : DEPTNO
SELECT * FROM DEPT; -- 부서 : DEPTNO

-- 5
SELECT EMPNO, ENAME, GRADE
FROM EMP E 
INNER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL
WHERE S.GRADE >= 3;

-- 6
SELECT JOB, TRUNC(AVG(S.GRADE))
FROM EMP E 
INNER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL
GROUP BY JOB
HAVING AVG(S.GRADE) >= 3;

-- 7 
SELECT JOB ,COUNT(*) 사람수
FROM EMP E 
INNER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL
GROUP BY JOB
HAVING AVG(S.GRADE) >= 3;

-- 8
SELECT D.DEPTNO, DNAME, AVG(E.SAL)
FROM EMP E 
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
GROUP BY D.DEPTNO, DNAME
HAVING AVG(E.SAL) >= 1800
