-- 1. STUDENT테이블에서 키가 큰 상위 5명 출력(중복고려 X, ROWNUM 사용)
-- 2. STUDENT테이블에서 키가 큰 상위 5명 출력(RANK 사용)

SELECT T.*
FROM (
    SELECT S.*
    FROM STUDENT S
    WHERE STU_HEIGHT IS NOT NULL
    ORDER BY STU_HEIGHT DESC
) T
WHERE ROWNUM <= 5;

SELECT T.*
FROM(
    SELECT S.* ,RANK() OVER(ORDER BY STU_HEIGHT DESC) RANK
    FROM STUDENT S
    WHERE STU_HEIGHT IS NOT NULL
) T
WHERE RANK <= 5;