-- PL/SQL (사용자 정의함수, TRIGGER, 프로시저 ..)

-- 선언부(선택), 실행부, 예외처리(선택)
-- 마지막을 '/'로 마무리

-- 숫자 2배로 리턴
CREATE OR REPLACE FUNCTION MULTI(I_VALUE IN NUMBER) -- INPUT의 I_VALUE
RETURN NUMBER
IS 
-- 변수 선언(선언부)
BEGIN
-- 실행부
    RETURN I_VALUE * 2;
END;
/

SELECT ENAME, SAL, MULTI(SAL)
FROM EMP;

SELECT * FROM TBL_POINT;

CREATE OR REPLACE FUNCTION DATE_FUNC (I_VALUE DATE)
RETURN VARCHAR2
IS 
BEGIN 
    RETURN TO_CHAR(I_VALUE, 'YYYY-MM-DD HH24:MI:SS');
END;
/

SELECT P.*, DATE_FUNC(CDATETIME) FROM TBL_POINT P;

-- DATE_FUNC2
--DATE_FUNC2(CDATETIME, 'DATE') => 'YYYY-MM-DD'
--DATE_FUNC2(CDATETIME, 'TIME') => 'HH24:MI:SS'
--DATE_FUNC2(CDATETIME, 'DATETIME') => 'YYYY-MM-DD HH24:MI:SS'

CREATE OR REPLACE FUNCTION DATE_FUNC2 (I_VALUE DATE, I_TYPE VARCHAR2)
RETURN VARCHAR2
IS
    O_DATE VARCHAR2(100);
BEGIN
    IF I_TYPE = 'DATETIME' THEN -- = 같다란 의미 , := 대입 (오라클)
        O_DATE := TO_CHAR(I_VALUE, 'YYYY-MM-DD HH24:MI:SS'); 
    ELSIF I_TYPE = 'DATE' THEN -- ELSIF 철자 조심
        O_DATE := TO_CHAR(I_VALUE, 'YYYY-MM-DD');  
    ELSIF I_TYPE = 'TIME' THEN
        O_DATE := TO_CHAR(I_VALUE, 'HH24:MI:SS');   
    ELSE 
        O_DATE := '값오류';
    END IF;
    RETURN O_DATE;
END;
/

SELECT CDATETIME, DATE_FUNC2(CDATETIME, 'DATETIME'),
DATE_FUNC2(CDATETIME, 'DATE'), 
DATE_FUNC2(CDATETIME, 'TIME'), 
DATE_FUNC2(CDATETIME, 'WIWIW') FROM TBL_POINT;

-- 7번째가 1이거나 3이면 '남' 리턴, 2거나 4면 '여' 리턴
-- 글자수가 13글자가 아니거나 1~4가 아니면 '알수없음' 리턴
SELECT GENDER_CHECK(JUMIN) FROM STU; 

CREATE OR REPLACE FUNCTION GENDER_CHECK(I_VALUE IN VARCHAR2)
RETURN VARCHAR2
IS
     O_VALUE VARCHAR2(20);
BEGIN
    IF LENGTH(I_VALUE) != 13 OR SUBSTR(I_VALUE, 7, 1) NOT IN('1','2','3','4')
        THEN O_VALUE := '알수없음';
    ELSIF SUBSTR(I_VALUE, 7, 1) IN('1', '3')
        THEN O_VALUE := '남';
    ELSE
        O_VALUE := '여';
    END IF;
    RETURN O_VALUE;
END;
/

-- 쌤 코드
CREATE OR REPLACE FUNCTION GENDER_CHECK(I_VALUE IN VARCHAR2)
RETURN VARCHAR2
IS
     O_VALUE VARCHAR2(20);
BEGIN
    O_VALUE := '알수없음';
    IF LENGTH(I_VALUE) = 13 AND SUBSTR(I_VALUE, 7, 1) IN('1', '3')
        THEN O_VALUE := '남';
    ELSIF LENGTH(I_VALUE) = 13 AND SUBSTR(I_VALUE, 7, 1) IN('2', '4')
        THEN O_VALUE := '여';
    END IF;
    RETURN O_VALUE;
END;
/

SELECT S.STU_NO, STU_NAME, STU_DEPT, ENR_GRADE, SOCRE_GRADE(ENR_GRADE) 성적
-- 90 ~ 100 A, 80~89 B, 70~79 C, 60~69 D, 나머지 F
-- 음수나 100초과는 없다고 가정하고 해.
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO;

-- 애초에 테이블에 입력을 음수나 100초과는 안받으니까 함수의 목적에 맞게 예외처리 안하는 것도 좋음.
CREATE OR REPLACE FUNCTION SOCRE_GRADE (I_SCORE IN NUMBER)
RETURN CHAR
IS 
    O_VALUE CHAR;
BEGIN
    IF I_SCORE BETWEEN 90 AND 100
        THEN O_VALUE := 'A';
    ELSIF I_SCORE >= 80
        THEN O_VALUE := 'B';
    ELSIF I_SCORE >= 70
        THEN O_VALUE := 'C';
    ELSIF I_SCORE >= 60
        THEN O_VALUE := 'D';
    ELSE
        O_VALUE := 'F';
    END IF;
    RETURN O_VALUE;
END;
/


