-- 트리거 <중요>
-- 특정(선택) 테이블에 변화가 생겼을 때 (DELETE, INSERT, UPDATE)
-- 실행되는 프로시저
-- 트리거는 거의 로그 기록용, 
-- 누군가가 불법적으로 데이터를 업데이트 한다거나 하면 로그에 기록이 남아서 증거가 됨

-- 샘플 트리거 생성

CREATE OR REPLACE TRIGGER TEMP_TRIGGER
    BEFORE -- 트리거 실행 시점(AFTER OR BEFORE)
    INSERT OR UPDATE ON STUDENT -- STUDENT 테이블이 INSERT 혹은 UPDATE가 발생했을 때 실행
    FOR EACH ROW -- 각 행 별로 트리거 실행
                -- EX) UPDATE로 3명의 정보가 변경되면 트리거도 3번 실행
BEGIN
    DBMS_OUTPUT.PUT_LINE('변경 전 : ' || :OLD.STU_HEIGHT);
    DBMS_OUTPUT.PUT_LINE('변경 후 : ' || :NEW.STU_HEIGHT);
END;
/

UPDATE STUDENT SET
    STU_HEIGHT = STU_HEIGHT+1
WHERE STU_NAME = '옥한빛';

-- 데베에 테이블, 데이터 날려버렸으면 빨리 말해야 복구가 쉬움. 로그에 남으니깐.
-- = 사고치면 빨리 말해라
-- 로그용
CREATE TABLE EMP_LOG(
    L_EMPNO NUMBER,
    O_SAL NUMBER,
    N_SAL NUMBER,
    O_COMM NUMBER,
    N_COMM NUMBER,
    L_ID VARCHAR2(50),-- 어떤 계정으로
    EVENT VARCHAR2(50), -- DELETE인지 INSERT인지..
    L_TIME DATE -- 언제 수정했는지
);

CREATE OR REPLACE TRIGGER EMP_TRIGGER
    BEFORE -- BEFORE여서 음수값 같은 입력값 차단 가능
    INSERT OR UPDATE OR DELETE ON EMP
    FOR EACH ROW
BEGIN
    IF INSERTING THEN -- INSERT가 발생하면 INSERTING이 TRUE로 바뀜
        IF :NEW.COMM IS NULL OR :NEW.COMM<0 THEN
            :NEW.COMM :=0;
        END IF;
        
        INSERT INTO EMP_LOG
        VALUES(:NEW.EMPNO, :NEW.SAL, :NEW.SAL, :NEW.COMM, :NEW.COMM, SYS_CONTEXT('USERENV', 'SESSION_USER'), 'I', SYSDATE);
        -- SYS_CONTEXT('USERENV', 'SESSION_USER')는 현재 접속 중인 계정 갖고 옴
        -- EVENT의 I는 INSERT 약자, UPDATE면 U 쓰면 되겠죠?
    ELSIF UPDATING THEN
        INSERT INTO EMP_LOG
        VALUES(:NEW.EMPNO, :OLD.SAL, :NEW.SAL, :OLD.COMM, :NEW.COMM, SYS_CONTEXT('USERENV', 'SESSION_USER'), 'U', SYSDATE);
    ELSIF DELETING THEN 
    -- 삭제 막고 싶어.
        RAISE_APPLICATION_ERROR(-20002, '사원데이터는 삭제 불가!' );
    END IF;
END;
/

UPDATE EMP SET
    SAL = SAL + 50
WHERE EMPNO = '7499';

COMMIT;
ROLLBACK;

SELECT * FROM EMP_LOG;

SELECT * FROM EMP;
INSERT INTO EMP
VALUES (1234, 'HONG', 'SALESMAN', '7698', SYSDATE, 2000, 200, 20);

DELETE FROM EMP 
WHERE EMPNO = 1234;


-- 문제
CREATE TABLE ENROL_LOG(
    L_SUBNO CHAR(3),
    L_STUNO CHAR(8),
    O_ENRGRADE NUMBER,
    N_ENRGRADE NUMBER,
    L_ID VARCHAR2(50),-- 어떤 계정으로
    EVENT VARCHAR2(50), -- DELETE인지 INSERT인지..
    L_TIME DATE -- 언제 수정했는지
);

CREATE OR REPLACE TRIGGER ENROL_TRIGGER
    BEFORE 
    INSERT OR UPDATE OR DELETE ON ENROL
    FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.ENR_GRADE NOT BETWEEN 0 AND 100 THEN
            :NEW.ENR_GRADE :=0;
        END IF;
        INSERT INTO ENROL_LOG
        VALUES(:NEW.SUB_NO, :NEW.STU_NO, :NEW.ENR_GRADE, :NEW.ENR_GRADE, SYS_CONTEXT('USERENV', 'SESSION_USER'), 'I', SYSDATE);
        
    ELSIF UPDATING THEN
        IF :NEW.ENR_GRADE NOT BETWEEN 0 AND 100 THEN
            RAISE_APPLICATION_ERROR(-20003, '시험점수 범위는 0~100입니다.' );
        END IF;
        INSERT INTO ENROL_LOG
        VALUES(:OLD.SUB_NO, :OLD.STU_NO, :OLD.ENR_GRADE, :NEW.ENR_GRADE, SYS_CONTEXT('USERENV', 'SESSION_USER'), 'U', SYSDATE);
        
    ELSIF DELETING THEN
        RAISE_APPLICATION_ERROR(-20004, '성적은 삭제 불가!');
    END IF;
END;
/

SELECT * FROM ENROL_LOG;
SELECT * FROM ENROL;

UPDATE ENROL SET
    ENR_GRADE = 105
WHERE STU_NO = '20152088';

DELETE FROM ENROL WHERE SUB_NO = 101;

