-- 시험대비 문제풀이1

-- 1 
SELECT *
FROM STUDENT
WHERE STU_DEPT = '컴퓨터정보';

-- 2
SELECT * FROM EMP;
INSERT INTO EMP (EMPNO, ENAME, MGR, SAL)
VALUES ('1010', 'KIM', '7902', 900);

-- 2-2
UPDATE EMP SET
    SAL = 2000
WHERE EMPNO = 1010;

-- 2-3
DELETE FROM EMP
WHERE EMPNO = 1010;

-- 4
SELECT * FROM STUDENT;
SELECT COUNT(*)
FROM STUDENT
WHERE STU_DEPT = '컴퓨터정보';

-- 5-1
SELECT * FROM STUDENT;
SELECT * FROM ENROL;
SELECT * FROM SUBJECT;

SELECT S.*
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN SUBJECT SUB ON E.SUB_NO = SUB.SUB_NO
WHERE SUB_DEPT = '컴퓨터정보';

-- 5-2
SELECT * FROM EMP;
SELECT * FROM SALGRADE;

SELECT EMPNO, ENAME, GRADE
FROM EMP E 
INNER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND HISAL;

-- 6
SELECT * FROM EMP;
SELECT *
FROM(
    SELECT E1.EMPNO, E1.ENAME, NVL(COUNT(E2.EMPNO),0) 부하직원수
    FROM EMP E1 
    LEFT JOIN EMP E2 ON E1.EMPNO = E2.MGR
    GROUP BY E1.EMPNO, E1.ENAME
    ORDER BY 부하직원수 DESC
) WHERE ROWNUM = 1;

-- 7
SELECT * FROM STUDENT;
SELECT * FROM ENROL;

SELECT TEST_CNT, AVG(ENR_GRADE)
FROM ENROL E
INNER JOIN (
    SELECT S.STU_NO, COUNT(*) TEST_CNT
    FROM STUDENT S 
    INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
    GROUP BY S.STU_NO
)T ON E.STU_NO = T.STU_NO
GROUP BY TEST_CNT;

-- 8
SELECT * FROM STUDENT;

SELECT T.STU_NO, STU_NAME, STU_DEPT, CNT
FROM STUDENT S
INNER JOIN (
    SELECT S1.STU_NO, NVL(COUNT(S2.STU_WEIGHT),0) CNT
    FROM STUDENT S1
    LEFT JOIN STUDENT S2 ON S1.STU_WEIGHT < S2.STU_WEIGHT
    GROUP BY S1.STU_NO
) T ON S.STU_NO = T.STU_NO;



-- 시험대비 문제풀이2
-- 1
SELECT *
FROM BOOK
WHERE PRICE >= 20000;

-- 2
SELECT *
FROM BOOK
WHERE BOOKNAME LIKE '%야구%';

-- 3
SELECT *
FROM BOOK
WHERE PUBLISHER = '굿스포츠'
ORDER BY BOOKNAME DESC;

-- 4
SELECT *
FROM BOOK
WHERE PRICE BETWEEN 5000 AND 20000;

-- 5
SELECT *
FROM CUSTOMER
WHERE PHONE IS NOT NULL AND CUSTID >= 3;

-- 6
SELECT * FROM BOOK; -- BOOKID
SELECT * FROM CUSTOMER; -- CUSTID
SELECT * FROM ORDERS; -- ORDERID 일단 얘로 다 합 가능

SELECT NAME, ROUND(AVG(SALEPRICE))
FROM CUSTOMER C
INNER JOIN ORDERS O ON C.CUSTID = O.CUSTID
GROUP BY C.CUSTID, NAME;

-- 7
SELECT SUBSTR(NAME, 1, 1), COUNT(SUBSTR(NAME, 1, 1))
FROM BOOK B
INNER JOIN ORDERS O ON B.BOOKID = O.BOOKID
INNER JOIN CUSTOMER C ON C.CUSTID = O.CUSTID
WHERE PUBLISHER = '이상미디어'
GROUP BY SUBSTR(NAME, 1, 1);

-- 8
SELECT ORDERID, ORDERDATE, NAME, O.BOOKID
FROM BOOK B
INNER JOIN ORDERS O ON B.BOOKID = O.BOOKID
INNER JOIN CUSTOMER C ON C.CUSTID = O.CUSTID
WHERE PUBLISHER = '이상미디어' AND TO_CHAR(ORDERDATE, 'YYYY-MM-DD') = '2020-07-07';

-- 9
SELECT CUSTID, NAME, ADDRESS, NVL(PHONE, '연락처없음')
FROM CUSTOMER;

-- 10
SELECT ORDERID, SALEPRICE
FROM ORDERS
WHERE SALEPRICE < (
    SELECT AVG(SALEPRICE)
    FROM ORDERS
);

-- 11
SELECT SUM(SALEPRICE)
FROM CUSTOMER C
INNER JOIN ORDERS O ON C.CUSTID = O.CUSTID
WHERE SUBSTR(ADDRESS,1,4) = '대한민국';

-- 12
SELECT ORDERID, SALEPRICE
FROM ORDERS
WHERE SALEPRICE >= (
    SELECT MAX(SALEPRICE)
    FROM CUSTOMER C
    INNER JOIN ORDERS O ON C.CUSTID = O.CUSTID
    WHERE C.CUSTID = 3
);

-- 13
SELECT NAME, SUM(SALEPRICE)
FROM BOOK B
INNER JOIN ORDERS O ON B.BOOKID = O.BOOKID
INNER JOIN CUSTOMER C ON C.CUSTID = O.CUSTID
WHERE PUBLISHER = '이상미디어'
GROUP BY C.CUSTID, NAME;

