-- UNION, UNION ALL

SELECT 
    STU_NO, STU_NAME, STU_DEPT
FROM STUDENT
WHERE STU_HEIGHT >= 170
UNION -- 중복없이 하나로 합쳐서 출력 (걍 합집합)
SELECT 
    STU_NO, STU_NAME, STU_DEPT
FROM STUDENT
WHERE STU_WEIGHT >= 60;


SELECT 
    STU_NO, STU_NAME, STU_DEPT
FROM STUDENT
WHERE STU_HEIGHT >= 170
UNION ALL -- 중복 제거 없이 그대로 출력(집합이 아님 그니까 중복처리 안해주지)
SELECT 
    STU_NO, STU_NAME, STU_DEPT
FROM STUDENT
WHERE STU_WEIGHT >= 60;


-- 주의점
-- 1. 컬럼의 개수가 동일해야 한다.
-- 2. 컬럼의 타입도 동일해야 한다.
-- 3. 컬럼이름(별칭)은 먼저 나오는 값을 기준으로 출력이 된다.
-- 4. 정렬(ORDER BY)는 맨 마지막에 작성. 첫번째 쿼리 컬럼을 기준으로 한다.

SELECT AVG(STU_HEIGHT) -- 숫자 
FROM STUDENT
UNION 
SELECT STU_NAME -- 문자
FROM STUDENT; -- 데이터 타입 달라서 오류

SELECT AVG(STU_HEIGHT) 
FROM STUDENT
UNION 
SELECT MAX(STU_HEIGHT), MIN(STU_HEIGHT)
FROM STUDENT; -- 컬럼 개수 달라서 오류

SELECT AVG(STU_HEIGHT) AS QQQ, COUNT(STU_HEIGHT) 
FROM STUDENT
UNION 
SELECT MAX(STU_HEIGHT) AS ZZZ, MIN(STU_HEIGHT) AS HHH
FROM STUDENT; -- 컬럼의 이름은 첫번째 쿼리 별칭 기준으로 출력

SELECT AVG(STU_HEIGHT) AS QQQ, COUNT(STU_HEIGHT) 
FROM STUDENT
UNION 
SELECT MAX(STU_HEIGHT) AS ZZZ, MIN(STU_HEIGHT) AS HHH
FROM STUDENT
ORDER BY QQQ; -- 정렬은 맨 마지막에, 합쳐진 이후에 한다.


-- 1. 학생들의 평균 점수 구하기
SELECT 
    STU_NAME, AVG(ENR_GRADE) AS AVG_GRADE
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY STU_NAME;
-- 2. 전체 평균 구하기
SELECT AVG(ENR_GRADE)
FROM ENROL; 
-- 3. 합치기
SELECT 
    STU_NAME, AVG(ENR_GRADE) AS AVG_GRADE, 1 AS ORDERKEY
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY STU_NAME
UNION
SELECT '전체평균', AVG(ENR_GRADE), 2 AS ORDERKEY 
-- 전체평균 레코드를 맨 밑으로 내리고자 ORDER KEY라는 컬럼 만들어서 그 컬럼을 ORDER BY함
FROM ENROL
ORDER BY ORDERKEY;

SELECT STU_NAME, AVG_GRADE
FROM (
    SELECT 
        STU_NAME, AVG(ENR_GRADE) AS AVG_GRADE, 1 AS ORDERKEY
    FROM STUDENT S
    INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
    GROUP BY STU_NAME
    UNION
    SELECT '전체평균', AVG(ENR_GRADE), 2 AS ORDERKEY 
    FROM ENROL
    ORDER BY ORDERKEY
);

-- EMP 
-- 직급별 평균 급여 출력
-- 마지막에는 전체 평균급여 출력
SELECT JOB, AVG_SAL
FROM(
    SELECT JOB, AVG(SAL) AVG_SAL, 1 AS ORDERKEY
    FROM EMP
    GROUP BY JOB
    UNION
    SELECT '전체평균', ROUND(AVG(SAL)), 2 AS ORDERKEY
    FROM EMP
)
ORDER BY ORDERKEY;

