-- RANK, DENSE_RANK, ROW_NUMBER
-- RANK써라
SELECT * FROM PROFESSOR;
SELECT * FROM STU;
SELECT * FROM DEPARTMENT;
-- 문제
-- 1
SELECT NAME, DNAME, PAY, SAL_RANK
FROM (
    SELECT NAME, DNAME, PAY, RANK() OVER(ORDER BY PAY DESC) SAL_RANK
    FROM PROFESSOR P 
    INNER JOIN DEPARTMENT D ON P.DEPTNO = D.DEPTNO
)
WHERE SAL_RANK <= 5;

-- 2
SELECT NAME, DNAME, PAY
FROM(
    SELECT NAME, DNAME, PAY, RANK() OVER(PARTITION BY P.DEPTNO ORDER BY PAY DESC) SAL_RANK
    FROM PROFESSOR P 
    INNER JOIN DEPARTMENT D ON P.DEPTNO = D.DEPTNO
)
WHERE SAL_RANK = 1;

-- 3
SELECT NAME, GENDER, HEIGHT
FROM(
    SELECT NAME, DECODE(SUBSTR(JUMIN,7,1),1,'남','여') GENDER, HEIGHT, RANK() OVER (PARTITION BY SUBSTR(JUMIN,7,1) ORDER BY HEIGHT DESC) HEIGHT_RANK
    FROM STU 
)
WHERE HEIGHT_RANK = 1;

-- 4
SELECT * FROM EMP;
SELECT DEPTNO, DNAME, DEPT_SAL 
FROM (
    SELECT E.DEPTNO, DNAME, RANK() OVER(ORDER BY AVG(SAL) DESC), AVG(SAL) DEPT_SAL
    FROM EMP E
    INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
    GROUP BY E.DEPTNO,DNAME
);