SELECT * FROM TBL_USER;
SELECT * FROM TBL_POINT;

-- 사용자 아이디, 이름, 잔여포인트 출력
SELECT U.USERID, NAME, BALANCE
FROM TBL_USER U
INNER JOIN (
    SELECT *
    FROM(
        SELECT USERID, BALANCE, RANK() OVER(PARTITION BY USERID ORDER BY CDATETIME DESC) RANK
        FROM TBL_POINT
    )
    WHERE RANK = 1
)T ON U.USERID = T.USERID;

-- '오지훈'의 현재 남은 포인트를 출력
SELECT U.USERID, NAME, BALANCE
FROM TBL_USER U
INNER JOIN (
    SELECT *
    FROM(
        SELECT USERID, BALANCE, RANK() OVER(PARTITION BY USERID ORDER BY CDATETIME DESC) RANK
        FROM TBL_POINT
    )
    WHERE RANK = 1 
)T ON U.USERID = T.USERID AND NAME = '오지훈'; -- 사람 수가 많아지면 느려질 여지 존재

-- 쌤 코드
SELECT USERID, NAME, BALANCE
FROM(
    SELECT U.USERID, NAME, BALANCE
    FROM TBL_USER U
    INNER JOIN TBL_POINT P ON U.USERID = P.USERID
    WHERE NAME = '오지훈'
    ORDER BY P.CDATETIME DESC
) WHERE ROWNUM = 1;

-- 'summerbox67' 아이디를 가진 사람의 포인트 변동 내역을 출력
-- 최신순으로 출력
-- 아이디, 이름, 잔여포인트, 내용

SELECT U.USERID, NAME, BALANCE, DESCRIPTION, P.CDATETIME
FROM TBL_USER U
INNER JOIN TBL_POINT P ON U.USERID = P.USERID
WHERE U.USERID = 'summerbox67'
ORDER BY P.CDATETIME DESC;

SELECT * FROM TBL_USER;
SELECT * FROM TBL_POINT;

SELECT U.*, 포인트변동횟수 -- 이 쿼리는 프로젝트 때 되게 유용함
FROM TBL_USER U
LEFT JOIN (
    SELECT USERID, NVL(COUNT(*), 0) 포인트변동횟수
    FROM TBL_POINT
    GROUP BY USERID
)T ON U.USERID = T.USERID;