-- ROUND(반올림), CEIL(올림), FLOOR(SOFLA), TRUNC(날림)
SELECT TRUNC(AVG(SAL),1)
FROM EMP;

-- ||
SELECT STU_GRADE || '학년'
FROM STUDENT;

-- LENGTH, SUBSTR
SELECT 
    ENAME, LENGTH(ENAME), SUBSTR(ENAME, 3), SUBSTR(ENAME, 2, 2)
FROM EMP;

SELECT * FROM STUDENT
WHERE SUBSTR(STU_NO, 3, 2) = '15';

SELECT SUBSTR(STU_NO, 3, 2) 학번 , AVG(STU_HEIGHT)
FROM STUDENT
GROUP BY SUBSTR(STU_NO, 3, 2);

SELECT TEL, LENGTH(TEL), INSTR(TEL, '-'), SUBSTR(TEL, 1, INSTR(TEL, '-')) || '****'
FROM STU;

--
SELECT
    SYSDATE, TO_CHAR(SYSDATE, 'YYYY.MM.DD HH24:MI:SS')
FROM DUAL;

SELECT * 
FROM EMP
WHERE TO_CHAR(HIREDATE, 'YY')= '81';

SELECT TO_CHAR(HIREDATE, 'YY') 입사년도, AVG(SAL) 
FROM EMP
GROUP BY TO_CHAR(HIREDATE, 'YY');

-- 그룹 함수
-- AVG, MAX, MIN, COUNT, SUM
SELECT STU_NAME, STU_HEIGHT
FROM STUDENT 
WHERE STU_HEIGHT = (
    SELECT MAX(STU_HEIGHT)
    FROM STUDENT
);

SELECT *
FROM (
    SELECT S.*, RANK() OVER(ORDER BY STU_HEIGHT DESC) RANK
    FROM STUDENT S
    WHERE STU_HEIGHT IS NOT NULL
) WHERE RANK = 1;


-- 학과별 가장 키가 큰 학생의 학번, 이름 키 출력
-- RANK
SELECT *
FROM(
    SELECT S.*, RANK() OVER(PARTITION BY STU_DEPT ORDER BY STU_HEIGHT DESC) RANK
    FROM STUDENT S
    WHERE STU_HEIGHT IS NOT NULL -- NULL 처리 주의!!!!
)WHERE RANK = 1;

--
SELECT * 
FROM EMP
WHERE SAL + NVL(COMM,0) >= 2500;

-- EMP 테이블에서 COMM이 NULL이면 '정보없음'으로 출력
SELECT E.*, NVL(TO_CHAR(COMM), '정보없음')
FROM EMP E;

-- DECODE(특정 값 = ), CASE WHEN(특정 사이값 >, <)
SELECT S.*, DECODE(STU_GENDER, 'M', '남자', 'F', '여자', '알수없음')
FROM STUDENT S;

-- 80점 이상 A, 60점 이상 B, 나머지 C
SELECT 
    E.*,
    CASE
        WHEN ENR_GRADE >= 80 THEN 'A'
        WHEN ENR_GRADE >= 60 THEN 'B'
        ELSE 'C'
    END 등급
FROM ENROL E;

