-- 조인
SELECT * FROM BOOK;
SELECT * FROM CUSTOMER;
SELECT * FROM ORDERS; -- 테이블명 원래 복수형 쓰지 않음. 단수형 씀.

-- 각 고객이 구매한 내역 출력
SELECT *
FROM CUSTOMER C
INNER JOIN ORDERS O ON C.CUSTID = O.CUSTID
INNER JOIN BOOK B ON B.BOOKID = O.BOOKID
ORDER BY NAME;

-- SELF JOIN
SELECT E1.ENAME, E2.ENAME
FROM EMP E1
INNER JOIN EMP E2 ON E1.MGR = E2.EMPNO;

-- 교수들이 속한 '대학' 출력
SELECT NAME, D3.DNAME
FROM DEPARTMENT D1
INNER JOIN DEPARTMENT D2 ON D1.PART = D2.DEPTNO
INNER JOIN DEPARTMENT D3 ON D2.PART = D3.DEPTNO
INNER JOIN PROFESSOR P ON D1.DEPTNO = P.DEPTNO;

-- EMP테이블에서 본인 급여등급보다 높은 급여등급을 가진 사람의 수 구하기
-- 사번, 이름, 급여등급, 사람 수 출력
SELECT * FROM SALGRADE;
SELECT E.EMPNO, E.ENAME, S.GRADE, NVL(COUNT(T.GRADE), 0) 
FROM EMP E
INNER JOIN SALGRADE S ON E.SAL BETWEEN LOSAL AND HISAL
LEFT JOIN (
    SELECT EMPNO, GRADE
    FROM EMP E
    INNER JOIN SALGRADE S ON E.SAL BETWEEN LOSAL AND HISAL
) T ON S.GRADE < T.GRADE
GROUP BY E.EMPNO, E.ENAME, S.GRADE;

-- 쌤 쿼리
SELECT EMPNO, ENAME, RANK() OVER(ORDER BY GRADE DESC) -1 AS 사람수, GRADE
-- RANK 특 : 중복 같은 순위, 건뛰 ㅇㅇ
FROM EMP E
INNER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL;

SELECT *
FROM CUSTOMER C
INNER JOIN (
    SELECT CUSTID, COUNT(*) AS CNT 
    FROM ORDERS
    GROUP BY CUSTID
) T ON C.CUSTID = T.CUSTID;

-- 본인학과에 속한 교수의 수
SELECT *
FROM PROFESSOR P
INNER JOIN (
    SELECT DEPTNO, COUNT(*) CNT 
    FROM PROFESSOR
    GROUP BY DEPTNO
) T ON P.DEPTNO = T.DEPTNO;

-- STU, 학번, 이름, 전공학과, 부전공학과 출력
SELECT STUNO, NAME, D1.DNAME, NVL(D2.DNAME, '부전공없음')
FROM STU S
INNER JOIN DEPARTMENT D1 ON S.DEPTNO1 = D1.DEPTNO
LEFT JOIN DEPARTMENT D2 ON S.DEPTNO2 = D2.DEPTNO;

-- STUDENT, ENROL 
-- 학번, 이름, 시험 본 개수 출력. 단, 시험을 안 본 학생은 0으로 출력
SELECT S.STU_NO, STU_NAME, NVL(COUNT(ENR_GRADE),0) CNT
FROM STUDENT S
LEFT JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY S.STU_NO, STU_NAME;

-- 학생들의 평균 점수를 기준으로 순위 매기기
SELECT S.STU_NO, STU_NAME, AVG(ENR_GRADE) 평균점수, RANK() OVER(ORDER BY AVG(ENR_GRADE) DESC) RANK
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY S.STU_NO, STU_NAME;

