-- 시험 테이블
-- EMP, DEPT, PROJECT, ASSIGNMENT
SELECT * FROM TBL_EMP; -- EMP_ID, DEPT_ID, MANAGER_ID(셀프조인)
SELECT * FROM TBL_DEPT; -- DEPT_ID, HEAD_ID
SELECT * FROM TBL_PROJECT; -- PROJ_ID, DEPT_ID
SELECT * FROM TBL_ASSIGNMENT; -- EMP_ID, PROJ_ID

-- 문제
-- 1
SELECT DEPT_NAME, AVG(SALARY) 평균급여
FROM TBL_EMP E
INNER JOIN TBL_DEPT D ON E.DEPT_ID = D.DEPT_ID
GROUP BY D.DEPT_ID, DEPT_NAME
ORDER BY AVG(SALARY) DESC;

-- 2
SELECT EMP_NAME, SALARY, TRUNC(HEAD_SAL) 
FROM TBL_EMP E
INNER JOIN (
    SELECT AVG(SALARY) HEAD_SAL
    FROM TBL_EMP E
    INNER JOIN TBL_DEPT D ON E.EMP_ID = D.HEAD_ID
)T ON 1 = 1
WHERE E.SALARY > T.HEAD_SAL;

-- 3
SELECT EMP_NAME, JOB_TITLE, SALARY
FROM TBL_EMP
WHERE SALARY = (
    SELECT MAX(SALARY)
    FROM TBL_PROJECT P
    INNER JOIN TBL_ASSIGNMENT A ON P.PROJ_ID = A.PROJ_ID
    INNER JOIN TBL_EMP E ON E.EMP_ID = A.EMP_ID
    WHERE PROJ_NAME = '모바일 앱 개발'
);

-- 4
SELECT E1.EMP_NAME, E1.JOB_TITLE, NVL(COUNT(E2.EMP_ID), 0) 부하직원수
FROM TBL_EMP E1
LEFT JOIN TBL_EMP E2 ON E1.EMP_ID = E2.MANAGER_ID
GROUP BY E1.EMP_ID, E1.EMP_NAME, E1.JOB_TITLE;

-- 5
SELECT PROJ_NAME, COUNT(EMP_ID) 투입인원수
FROM TBL_PROJECT P
INNER JOIN TBL_EMP E ON P.DEPT_ID = E.DEPT_ID
GROUP BY PROJ_ID, PROJ_NAME;



CREATE OR REPLACE PROCEDURE EMPINFO_PROC(I_EMPNO EMP.EMPNO%TYPE)
IS
    O_ENAME EMP.ENAME%TYPE;
    O_JOB EMP.JOB%TYPE;
    O_SAL EMP.SAL%TYPE;
BEGIN
    SELECT ENAME, JOB, SAL
    -- ENAME, JOB, SAL은 이 쿼리 안에서만 존재하는 지역변수
    -- 그래서 프린트 문에서 못씀
    INTO O_ENAME, O_JOB, O_SAL
    -- INTO를 통해 변수에 담아줌 
    FROM EMP
    WHERE EMPNO = I_EMPNO;
    DBMS_OUTPUT.PUT_LINE(O_ENAME || '님의 직급은 ' || O_JOB || ', 급여는 ' || O_SAL);
END;
/
