SELECT * FROM BOARD;
INSERT INTO BOARD (TITLE, CONTENTS, USERID)
VALUES ('다그닥다그닥', '말은 간다', 'TEST1');

INSERT INTO BOARD
VALUES(NULL, '왈왈', '강아지가 짖는다', 'TEST2', 0, NOW(), NOW());
-- AI 컬럼엔 NULL 넣으면 됨.


SELECT * FROM BOARD_COMMENT;
INSERT INTO BOARD_COMMENT
VALUES (NULL, 1, '휘적휘적 나그네가 방황한다','TE1' , NOW(), NOW());

SELECT * FROM BOARD_COMMENT;
INSERT INTO BOARD_COMMENT
VALUES (NULL, 1, 'ㅎㅎ','TE2' , NOW(), NOW());

SELECT * FROM BOARD_COMMENT;
INSERT INTO BOARD_COMMENT
VALUES (NULL, 2, '윙윙','TE1' , NOW(), NOW());

SELECT * 
FROM BOARD B
INNER JOIN BOARD_COMMENT C ON B.BOARDNO = C.BOARDNO;
-- ANCI문법(현재 대부분)

-- 

SELECT CONCAT(BOARDNO, TITLE, CONTENTS) -- MYSQL에선 CONCAT인자 개수 제한없음
FROM BOARD;

--

SELECT IFNULL(CNT, 100) -- NVL과 동일
FROM BOARD;

-- 디코드같은 조건에 맞는 값 필요하면 여긴 DECODE 없으니까 CASE문 쓰면 됨

SELECT TRUNCATE(100.232, 0); -- DUAL 필요 없음

SELECT 
	DATE_FORMAT(CDATETIME, '%Y'),
    DATE_FORMAT(CDATETIME, '%y'),
    DATE_FORMAT(CDATETIME, '%M'),
    DATE_FORMAT(CDATETIME, '%m'),
    DATE_FORMAT(CDATETIME, '%D'),
    DATE_FORMAT(CDATETIME, '%d'),
    DATE_FORMAT(CDATETIME, '%H'), -- 24기준
    DATE_FORMAT(CDATETIME, '%h'),
    DATE_FORMAT(CDATETIME, '%i'),
    DATE_FORMAT(CDATETIME, '%s'),
	DATE_FORMAT(CDATETIME, '%Y.%m.%d %H:%i:%s')
FROM BOARD_COMMENT;