-- 1
SELECT EMPNO, ENAME, SAL
FROM EMP
WHERE SAL >= 3000;

-- 2
INSERT INTO TBL_EMP
VALUES ('E1008', '김나리', '사원', 'E1004', SYSDATE, 3000000, 'D02');
--
UPDATE TBL_EMP SET
    SALARY = SALARY*0.1 + SALARY
WHERE EMP_ID = 'E1008';
--
DELETE FROM TBL_EMP
WHERE EMP_ID = 'E1008';

-- 3
SELECT STU_NO, 
    CASE
        WHEN ENR_GRADE >= 80 THEN 'A'
        WHEN ENR_GRADE >= 70 THEN 'B'
        WHEN ENR_GRADE >= 60 THEN 'C'
        ELSE '노력요망'
    END GRADE
FROM ENROL;

-- 4
SELECT COUNT(*)
FROM PROFESSOR
WHERE POSITION = '정교수';

-- 5
SELECT SUBSTR(EMAIL, 1, INSTR(EMAIL, '@')-1)
FROM PROFESSOR;

-- 6
SELECT TO_CHAR(HIREDATE, 'MM')||'월' 월, COUNT(*)
FROM PROFESSOR
GROUP BY TO_CHAR(HIREDATE, 'MM')
ORDER BY 월;

-- 7
SELECT PROFNO, NAME, POSITION, DNAME
FROM PROFESSOR P
INNER JOIN DEPARTMENT D ON P.DEPTNO = D.DEPTNO
WHERE DNAME = '컴퓨터공학과';
--
SELECT STUNO, NAME, NVL(TO_CHAR(DNAME), '해당없음') 부전공 
FROM STU S
LEFT JOIN DEPARTMENT D ON S.DEPTNO2 = D.DEPTNO;

-- 8
SELECT E1.EMPNO, E1.ENAME
FROM EMP E1
LEFT JOIN EMP E2 ON E1.EMPNO = E2.MGR
GROUP BY E1.EMPNO, E1.ENAME
HAVING COUNT(E2.EMPNO) = 0;

-- 9
SELECT PROFNO, NAME, PAY, NVL(TO_CHAR(BONUS),'없음')
FROM(
    SELECT PROFNO, NAME, PAY, BONUS, RANK() OVER(ORDER BY BONUS DESC) RANK
    FROM PROFESSOR
    WHERE BONUS IS NOT NULL
    UNION
    SELECT PROFNO, NAME, PAY, BONUS, 100
    FROM PROFESSOR
    WHERE BONUS IS NULL 
) ORDER BY RANK;

-- 10
SELECT D.DEPT_ID, DEPT_NAME, LOCATION, E.EMP_NAME, CNT
FROM TBL_EMP E
INNER JOIN TBL_DEPT D ON D.HEAD_ID = E.EMP_ID
INNER JOIN (
    SELECT D.DEPT_ID, COUNT(*) CNT
    FROM TBL_EMP E
    INNER JOIN TBL_DEPT D ON E.DEPT_ID = D.DEPT_ID
    GROUP BY D.DEPT_ID
)T ON D.DEPT_ID = T.DEPT_ID;


-- 11
SELECT E1.EMP_ID, E1.EMP_NAME, DEPT_NAME, COUNT(E2.EMP_ID)
FROM TBL_EMP E1
INNER JOIN TBL_DEPT D ON E1.DEPT_ID = D.DEPT_ID
LEFT JOIN TBL_EMP E2 ON E1.SALARY < E2.SALARY
GROUP BY E1.EMP_ID, E1.EMP_NAME, DEPT_NAME;


-- 12

SELECT EMP_ID, EMP_NAME, PROJ_NAME, DEPT_NAME, CNT
FROM TBL_PROJECT P
INNER JOIN TBL_DEPT D ON P.DEPT_ID = D.DEPT_ID
RIGHT JOIN TBL_EMP E ON D.DEPT_ID = E.DEPT_ID
LEFT JOIN (
    SELECT PROJ_ID, COUNT(EMP_ID) CNT
    FROM TBL_PROJECT P
    INNER JOIN TBL_DEPT D ON P.DEPT_ID = D.DEPT_ID
    INNER JOIN TBL_EMP E ON D.DEPT_ID = E.DEPT_ID
    GROUP BY PROJ_ID
) T ON P.PROJ_ID = T.PROJ_ID;


-- 13
SELECT DEPT_NAME, SUM_SAL
FROM(
    SELECT DEPT_NAME, SUM(SALARY) SUM_SAL
    FROM TBL_EMP E 
    INNER JOIN TBL_DEPT D ON E.DEPT_ID = D.DEPT_ID
    GROUP BY D.DEPT_ID, DEPT_NAME
    ORDER BY SUM(SALARY) DESC
) WHERE ROWNUM = 1;

-- 14
SELECT '3등급이상' 카테고리, COUNT(*) 인원수
FROM EMP E
INNER JOIN SALGRADE S ON E.SAL BETWEEN LOSAL AND HISAL
WHERE GRADE >= 3
UNION
SELECT '3등급미만', COUNT(*)
FROM EMP E
INNER JOIN SALGRADE S ON E.SAL BETWEEN LOSAL AND HISAL
WHERE GRADE < 3;




