-- 그룹 함수
-- AVG, MAX, MIN, COUNT, SUM

-- 학생들의 전체 키 평균
SELECT AVG(STU_HEIGHT) FROM STUDENT;

-- 학과별 학생들의 전체 키 평균
SELECT AVG(STU_HEIGHT) FROM STUDENT
GROUP BY STU_DEPT;

-- 학과별 학생들의 키 평균
-- 단, 170 이상만 대상으로 한다 => WHERE
SELECT STU_DEPT, AVG(STU_HEIGHT) FROM STUDENT
WHERE STU_HEIGHT >= 170
GROUP BY STU_DEPT;

-- 평균키가 175 이상인 학과 + 평균키만 출력 => HAVING
SELECT STU_DEPT, AVG(STU_HEIGHT) FROM STUDENT
GROUP BY STU_DEPT
HAVING AVG(STU_HEIGHT) >= 175;

-- COUNT는 컬럼명을 넣었을 때 NULL 값은 제외하고 카운트
SELECT 
    COUNT(*),
    COUNT(STU_NO),
    COUNT(STU_HEIGHT)
FROM STUDENT;

-- 조인 INNER JOIN
SELECT *
FROM ENROL;

-- 학번 => STUDENT, ENROL, (이름, 학과) => STUDENT, 점수 => ENROL , 과목명 => SUBJECT

SELECT 
    S.STU_NO, STU_NAME, STU_DEPT, ENR_GRADE, SUB_NAME
FROM STUDENT S 
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN SUBJECT SUB ON E.SUB_NO = SUB.SUB_NO;

-- EMP
SELECT * FROM EMP;
SELECT * FROM SALGRADE;
SELECT *
FROM EMP E
INNER JOIN SALGRADE S ON E.SAL BETWEEN LOSAL AND HISAL;


