-- SELF JOIN(자가 조인)

SELECT E1.EMPNO, E1.ENAME, E2.ENAME
FROM EMP E1
INNER JOIN EMP E2 ON E1.MGR = E2.EMPNO;
 
SELECT * FROM DEPARTMENT;
SELECT * FROM STU;

-- 학과, 학부, 대학 출력
SELECT D1.DNAME, D2.DNAME, D3.DNAME
FROM DEPARTMENT D1
INNER JOIN DEPARTMENT D2 ON D1.PART = D2.DEPTNO
INNER JOIN DEPARTMENT D3 ON D2.PART = D3.DEPTNO;

-- '공과대학'에 속한 학생들 출력(주전공 - DEPTNO1 기준)
SELECT S.STUNO, S.NAME, D1.DNAME, D2.DNAME
FROM DEPARTMENT D1
INNER JOIN STU S ON D1.DEPTNO = S.DEPTNO1
INNER JOIN DEPARTMENT D2 ON D1.PART = D2.DEPTNO
INNER JOIN DEPARTMENT D3 ON D2.PART = D3.DEPTNO
WHERE D3.DNAME = '공과대학';

SELECT * FROM PROFESSOR;
-- 각 대학별(공과대학, 인문대학) 교수의 수 구하기
SELECT D3.DNAME, COUNT(*) 교수수
FROM DEPARTMENT D1
INNER JOIN PROFESSOR P ON D1.DEPTNO = P.DEPTNO
INNER JOIN DEPARTMENT D2 ON D1.PART = D2.DEPTNO
INNER JOIN DEPARTMENT D3 ON D2.PART = D3.DEPTNO
GROUP BY D3.DNAME;

-- 본인의 부하직원 수 구하기(이름, 부하직원 수 출력)
SELECT E1.ENAME, COUNT(*) 부하직원수
FROM EMP E1 
INNER JOIN EMP E2 ON E1.EMPNO = E2.MGR -- 반대로 해도 되는데 이게 *로 출력해봤을 때 더 깔끔하긴 해
GROUP BY E1.EMPNO, E1.ENAME;
