-- 서브쿼리 : 쿼리 안에 또 다른 쿼리
-- STUDENT, 가장 큰 값은 구할 수 있지만 큰 값을 가진 사람이 누구인지 구할 수 없음.
-- 그룹함수라서..
-- 그래서 서브쿼리를 씀.
SELECT MAX(STU_HEIGHT)
FROM STUDENT;

SELECT *
FROM STUDENT
WHERE STU_HEIGHT = (
    SELECT MAX(STU_HEIGHT)
    FROM STUDENT -- =로 비교하고 있으니 컬럼과 레코드 1개만 나와야 함.
);

-- UNION => 나중에 자세히, 결과 합치는 기능
SELECT MAX(STU_HEIGHT) AS HEIGHT
FROM STUDENT
UNION
SELECT MIN(STU_HEIGHT) AS HEIGHT
FROM STUDENT;

-- 2개 이상의 레코드 조건절에서 서브쿼리
SELECT *
FROM STUDENT
WHERE STU_HEIGHT IN (-- IN은 컬럼이 여러개면 안되고(컬럼은 하나여야 한다는 말) 레코드가 여러개 여야 함ㅇㅇ
    SELECT MAX(STU_HEIGHT) AS HEIGHT
    FROM STUDENT
    UNION
    SELECT MIN(STU_HEIGHT) AS HEIGHT
    FROM STUDENT
);

SELECT STU_DEPT, MAX(STU_HEIGHT)
FROM STUDENT
GROUP BY STU_DEPT; -- 이 키 값 누구인지 알고 싶음

-- 아래처럼 하면 다른 학과의 동일 키를 가진 학생도 조회될 수 있다.
SELECT *
FROM STUDENT
WHERE STU_HEIGHT IN (
    SELECT MAX(STU_HEIGHT)
    FROM STUDENT
    GROUP BY STU_DEPT
    -- 학과별 정보는 버리고 키값만 가져가서 그냥 여기의 키값 레코드랑 똑같은 값 다 나오게 됨.
    -- 원래 의도는 학과별 제일 큰 사람만 출력하려 했는데 그냥 같은 값이면 나오는 불상사 발생.
    -- 그래서 이렇게 하면 안됨!
);


SELECT *
FROM STUDENT
WHERE (STU_DEPT, STU_HEIGHT) IN ( -- 이렇게 두 개를 비교하면 과별 젤 큰 사람 나옴!
    SELECT STU_DEPT, MAX(STU_HEIGHT)
    FROM STUDENT
    GROUP BY STU_DEPT
);

-- PROFESSOR
-- 각 직급별 가장 높은 급여를 받는 교수의 이름, 직급, 급여 출력
SELECT * FROM PROFESSOR;

SELECT NAME, POSITION, PAY+NVL(BONUS,0) 급여
FROM PROFESSOR
WHERE (POSITION, PAY+NVL(BONUS,0)) IN(
    SELECT POSITION, MAX(PAY+NVL(BONUS,0))
    FROM PROFESSOR
    GROUP BY POSITION
);

-- STUDENT, ENROL
-- 본인의 학과 평균 점수보다 높은 평균점수를 가진 학생의 학번, 이름, 점수 출력
SELECT * FROM STUDENT;
SELECT * FROM ENROL;

SELECT STU_DEPT, AVG(ENR_GRADE) AS DEPT_SCORE
FROM STUDENT S 
INNER JOIN ENROL E ON E.STU_NO = S.STU_NO
GROUP BY STU_DEPT;

SELECT S.STU_NO, STU_NAME, S.STU_DEPT, AVG(ENR_GRADE) AS AVG_SCORE, DEPT_SCORE
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN (
    SELECT STU_DEPT, AVG(ENR_GRADE) AS DEPT_SCORE
    FROM STUDENT S 
    INNER JOIN ENROL E ON E.STU_NO = S.STU_NO
    GROUP BY STU_DEPT
) T ON T.STU_DEPT = S.STU_DEPT
GROUP BY S.STU_NO, STU_NAME, S.STU_DEPT, DEPT_SCORE
HAVING AVG(ENR_GRADE) >= DEPT_SCORE
ORDER BY S.STU_DEPT;

-- 예시
SELECT *
FROM (
    SELECT STU_NO, STU_NAME, STU_DEPT
    FROM STUDENT
);

--  본인 학과의 평균 키보다 큰 학생들 출력
SELECT STU_NO, STU_NAME, S.STU_DEPT, STU_HEIGHT, DEPT_HEIGHT
FROM STUDENT S
INNER JOIN (
    SELECT STU_DEPT, AVG(STU_HEIGHT) DEPT_HEIGHT
    FROM STUDENT
    GROUP BY STU_DEPT
) T ON S.STU_DEPT = T.STU_DEPT
WHERE STU_HEIGHT > DEPT_HEIGHT;

-- 문제
SELECT * FROM PROFESSOR;
-- 1
SELECT PROFNO, NAME, PAY
FROM PROFESSOR
WHERE PAY = (
    SELECT MAX(PAY)
    FROM PROFESSOR
);

-- 2
SELECT PROFNO, NAME, PAY
FROM PROFESSOR P
WHERE PAY > (
    SELECT AVG(PAY)
    FROM PROFESSOR
);

-- 3
SELECT PROFNO, NAME, PAY
FROM PROFESSOR P
INNER JOIN (
    SELECT POSITION, AVG(PAY) POSITION_AVG
    FROM PROFESSOR
    GROUP BY POSITION
)T ON P.POSITION = T.POSITION
WHERE PAY > POSITION_AVG;


SELECT * FROM EMP;
SELECT * FROM SALGRADE;
SELECT * FROM DEPT;
-- 4
SELECT EMPNO, ENAME, SAL
FROM EMP
WHERE SAL IN(
    SELECT MAX(SAL)
    FROM EMP
    UNION
    SELECT MIN(SAL)
    FROM EMP
);

-- 5
SELECT EMPNO, ENAME, DNAME, SAL
FROM EMP E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
WHERE (E.DEPTNO, SAL) IN(
    SELECT E.DEPTNO, MAX(SAL)
    FROM EMP E
    INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
    GROUP BY E.DEPTNO, DNAME
    UNION
    SELECT E.DEPTNO, MIN(SAL)
    FROM EMP E
    INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
    GROUP BY E.DEPTNO, DNAME
)
ORDER BY E.DEPTNO;

-- 쌤 코드
SELECT EMPNO, ENAME, DNAME, SAL
FROM EMP E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
INNER JOIN (
    SELECT DEPTNO, MAX(SAL) AS MAX_SAL, MIN(SAL) AS MIN_SAL
    FROM EMP
    GROUP BY DEPTNO
) T ON E.DEPTNO = T.DEPTNO
WHERE SAL IN (MAX_SAL, MIN_SAL);

-- 6
SELECT EMPNO, ENAME, GRADE
FROM EMP E
INNER JOIN SALGRADE D ON E.SAL BETWEEN LOSAL AND HISAL
INNER JOIN (
    SELECT JOB, AVG(GRADE) JOB_GRADE
    FROM EMP E
    INNER JOIN SALGRADE D ON E.SAL BETWEEN LOSAL AND HISAL
    GROUP BY JOB
) T ON E.JOB = T.JOB
WHERE GRADE > JOB_GRADE;



