-- OUTER 조인 (LEFT 위주)

SELECT *
FROM STUDENT S -- 시험을 안 본 친구는 조회되지 않음
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO;

-- 각 시험평균점수 출력, 시험을 안 본 학생은 '점수없음' 출력
SELECT *
FROM STUDENT S 
LEFT JOIN ENROL E ON S.STU_NO = E.STU_NO;

SELECT S.STU_NO, STU_NAME, NVL(TO_CHAR(AVG(ENR_GRADE)), '점수없음') 
FROM STUDENT S -- NVL은 두 인자가 같은 자료형이길 원함. 그래서 TO_CHAR로 감싼 거
LEFT JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY S.STU_NO, STU_NAME;

-- 각 학생들이 본 시험의 수 출력
-- 시험을 안 본 친구들 0으로 출력
SELECT S.STU_NO, STU_NAME,NVL(COUNT(ENR_GRADE),0)
FROM STUDENT S 
LEFT JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY S.STU_NO, STU_NAME;

-- PROFESSOR
SELECT * FROM PROFESSOR;
SELECT * FROM STU;

-- 1. 학생이름, 담당교수 이름 출력. 담당교수 없으면 '담당없음'으로 출력
SELECT S.NAME, NVL(P.NAME, '담당없음') 담당교수
FROM STU S
LEFT JOIN PROFESSOR P ON S.PROFNO = P.PROFNO;

-- 2. 각 교수가 담당하고 있는 학생의 수 출력. 없으면 0으로 출력
SELECT P.NAME, NVL(COUNT(S.NAME), 0) 학생수
FROM PROFESSOR P 
LEFT JOIN STU S ON S.PROFNO = P.PROFNO
GROUP BY P.PROFNO, P.NAME;

-- EMP
SELECT * FROM EMP;

-- 부하직원의 수 구하기. 없으면 0으로 출력
SELECT E1.ENAME, NVL(COUNT(E2.ENAME),0) 부하수
FROM EMP E1
LEFT JOIN EMP E2 ON E1.EMPNO = E2.MGR
GROUP BY E1.EMPNO, E1.ENAME;

-- 
SELECT 
    NAME, D1.DNAME, D2.DNAME
FROM STU S
INNER JOIN DEPARTMENT D1 ON S.DEPTNO1 = D1.DEPTNO -- 주전공 있는 애들
LEFT JOIN DEPARTMENT D2 ON S.DEPTNO2= D2.DEPTNO -- 결국 부전공 없는 애들도 포함해서
