-- 문제

-- STUDENT, ENROL, SUBJECT 
SELECT * FROM STUDENT;
SELECT * FROM ENROL;
SELECT * FROM SUBJECT;
-- 1
SELECT STU_NO, STU_NAME, STU_DEPT
FROM STUDENT
WHERE STU_NAME LIKE '김%';

-- 2
SELECT STU_NO, STU_NAME, STU_DEPT
FROM STUDENT
WHERE SUBSTR(STU_NO, 3,2) = 15;

-- 3
SELECT AVG(ENR_GRADE)
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO 
WHERE STU_DEPT = '컴퓨터정보';

-- 4
SELECT S.STU_NO, STU_NAME, STU_DEPT, ENR_GRADE
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO 
INNER JOIN SUBJECT SUB ON SUB.SUB_NO = E.SUB_NO
WHERE SUB_NAME = '컴퓨터개론';

-- 5
SELECT STU_NO, STU_NAME, STU_HEIGHT
FROM STUDENT
WHERE STU_HEIGHT > (
    SELECT AVG(STU_HEIGHT)
    FROM STUDENT
);

-- 6
SELECT STU_NO, STU_NAME, STU_HEIGHT, DEPT_HEIGHT
FROM STUDENT S
INNER JOIN (
    SELECT STU_DEPT, AVG(STU_HEIGHT) DEPT_HEIGHT
    FROM STUDENT
    GROUP BY STU_DEPT
) T ON S.STU_DEPT = T.STU_DEPT
WHERE S.STU_HEIGHT > DEPT_HEIGHT;

-- 7
SELECT STU_DEPT, AVG(ENR_GRADE)
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO 
GROUP BY STU_DEPT
HAVING AVG(ENR_GRADE) < (
    SELECT AVG(ENR_GRADE)
    FROM STUDENT S
    INNER JOIN ENROL E ON S.STU_NO = E.STU_NO 
    WHERE STU_DEPT = '컴퓨터정보'
);


SELECT * FROM EMP;
SELECT * FROM SALGRADE;
SELECT * FROM DEPT;
-- 1
SELECT E1.EMPNO, E1.ENAME, E2.ENAME 팀장 
FROM EMP E1
INNER JOIN EMP E2 ON E1.MGR = E2.EMPNO;

-- 2
SELECT E.EMPNO, E.ENAME, E.SAL, D.DNAME
FROM EMP E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
WHERE (E.DEPTNO, SAL) IN (
    SELECT D.DEPTNO, MAX(SAL)
    FROM EMP E 
    INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
    GROUP BY D.DEPTNO, DNAME
);

-- 3
SELECT SUM(SAL)
FROM EMP
WHERE TO_CHAR(HIREDATE, 'YY') = '81';

-- 4 : 좀 복잡하게 풀음 다시 풀어봐
SELECT JOB, SUM(SAL)
FROM EMP
GROUP BY JOB
HAVING SUM(SAL) = (
    SELECT MAX(SAL_SUM)
    FROM(
    SELECT JOB, SUM(SAL) SAL_SUM
    FROM EMP
    GROUP BY JOB
    )
);

-- 5
SELECT ENAME, DNAME
FROM EMP E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
WHERE (JOB, D.DEPTNO) IN (
    SELECT JOB, D.DEPTNO
    FROM EMP E
    INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
    WHERE ENAME = 'ALLEN'
);

-- 1
SELECT * FROM STU;
SELECT * FROM PROFESSOR;
SELECT * FROM DEPARTMENT;

SELECT COUNT(*)
FROM STU S
INNER JOIN DEPARTMENT D1 ON S.DEPTNO1 = D1.DEPTNO
INNER JOIN DEPARTMENT D2 ON D1.PART = D2.DEPTNO
INNER JOIN DEPARTMENT D3 ON D2.PART = D3.DEPTNO
WHERE D3.DNAME = '공과대학' AND SUBSTR(JUMIN, 7, 1) IN (1, 3);

-- 2
SELECT NAME, ID, DNAME
FROM PROFESSOR P
INNER JOIN DEPARTMENT D ON P.DEPTNO = D.DEPTNO
WHERE PAY + NVL(BONUS,0) <= 400;

-- 3
SELECT P.NAME, P.ID, P.PROFNO, 담당학생수
FROM PROFESSOR P
INNER JOIN STU S ON P.PROFNO = S.PROFNO
INNER JOIN (
    SELECT P.PROFNO, COUNT(S.NAME) 담당학생수
    FROM PROFESSOR P
    INNER JOIN STU S ON P.PROFNO = S.PROFNO
    GROUP BY P.PROFNO
)T ON P.PROFNO = T.PROFNO
WHERE 담당학생수 >= 2;

-- 4
SELECT DNAME, COUNT(S.STUNO)
FROM STU S
INNER JOIN DEPARTMENT D ON S.DEPTNO1 = D.DEPTNO
GROUP BY DNAME
HAVING COUNT(S.STUNO) IN(
SELECT MAX(COUNT(S.STUNO))
FROM STU S
INNER JOIN DEPARTMENT D ON S.DEPTNO1 = D.DEPTNO
GROUP BY DNAME
UNION
SELECT MIN(COUNT(S.STUNO))
FROM STU S
INNER JOIN DEPARTMENT D ON S.DEPTNO1 = D.DEPTNO
GROUP BY DNAME
);


-- 이전반시험문제
SELECT S.STUNO, S.NAME, S.GRADE, 높은학년사람수
FROM STU S
INNER JOIN (
    SELECT S1.STUNO, COUNT(S2.STUNO) 높은학년사람수
    FROM STU S1
    INNER JOIN STU S2 ON S1.GRADE < S2.GRADE
    GROUP BY S1.STUNO
)T ON S.STUNO = T.STUNO;

SELECT * FROM PROFESSOR;

SELECT EMAIL, 
LPAD(SUBSTR(EMAIL, INSTR(EMAIL,'@') , 1) ,LENGTH(SUBSTR(EMAIL, 1 ,INSTR(EMAIL,'@')-1)),'*') ||
LPAD(SUBSTR(EMAIL, -4 , LENGTH(EMAIL)), LENGTH(SUBSTR(EMAIL, INSTR(EMAIL,'@')+1 ,LENGTH(EMAIL))), '*')
FROM PROFESSOR;


