SELECT * FROM STU;
SELECT * FROM PROFESSOR;
SELECT * FROM DEPARTMENT;

-- 학번, 학생이름,) -> STU 학과,) -> DEPAR 담당교수명 출력
SELECT STUNO, S.NAME , DNAME, P.NAME PROFNAME
FROM STU S 
INNER JOIN PROFESSOR P ON S.PROFNO = P.PROFNO
INNER JOIN DEPARTMENT D ON D.DEPTNO = S.DEPTNO1;

-- 각 학과별 학생 수 출력(학과명, 학생 수 출력)
SELECT DNAME, COUNT(*) 학생수
FROM STU S 
INNER JOIN DEPARTMENT D ON D.DEPTNO = S.DEPTNO1
GROUP BY DEPTNO, DNAME; 



